name: Build & Deploy to S3 + CloudFront

on:
  workflow_call:      
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      S3_BUCKET:
        required: true
      REGION:
        required: true
      CLOUDFRONT_DISTRIBUTION:
        required: true

defaults:
  run:
    working-directory: app/web-interface

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build --if-present

      - name: List build output (debug)
        run: ls -R dist

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}

      - name: Sync files to S3
        run: |
          aws s3 sync dist/ s3://$S3_BUCKET_NAME/ --delete
        env:
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET }}
      
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
            --paths "/*"
        env:
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION }}


      # - name: Sync build output to S3
      #   uses: aws-actions/s3-sync@v2
      #   with:
      #     source: dist/
      #     destination: ${{ inputs.s3_bucket }}
      #     region: ${{ inputs.region }}
      #     delete: true
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # - name: Invalidate CloudFront cache
      #   uses: aws-actions/aws-cloudfront-invalidate@v3
      #   with:
      #     distribution-id: ${{ inputs.CLOUDFRONT_DISTRIBUTION }}
      #     paths: "/*"
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: ${{ inputs.region }}
