name: Web App - Lint, Test

on:
  pull_request:
    paths:
      - "app/web-interface/**"

jobs:
  lint:
    uses: ./.github/workflows/jobs/web-app-lint.yml

  test:
    uses: ./.github/workflows/jobs/web-app-test.yml
